### ISSUE TITLE
No grammar for string literals; impossible to end a string with backslash

### ISSUE THREAD

**Issue by yeputons** [liam-ilan/crumb#4]
It seems to me that the lexer is ad-hoc with no specific grammar for what it's trying to lex: https://github.com/liam-ilan/crumb/blob/5ff70a23fa7df4bf8a6404ebbf164c54d7cac1a8/src/lex.c#L53-L85

In particular, it seems to assume that `\"` always terminates the string literal. It's not the standard behavior for other programming languages; one can escape the backslash with another backslash, e.g. `"\\"`.

**Comment by liam-ilan** [comment]
Fixed by skipping escape codes as they are scanned, rather than creating a special condition just for \".

**Comment by h2oboi89** [comment]
is your intention to not allow escaped codes in strings?

`if (code[i] == '\\') i++;` should result in `(print (factorial (integer (input))) "\n")` parsing as `(print (factorial (integer (input))) "n")` now.

**Comment by yeputons** [comment]
@h2oboi89 should be fine, the code in `lex.c` just detects a string literal, the `parseString` call below actually takes care of converting escape codes to data:

https://github.com/liam-ilan/crumb/blob/c8b916ee4e503ae4f9617a45fa445cfa781bc50a/src/lex.c#L85

https://github.com/liam-ilan/crumb/blob/c8b916ee4e503ae4f9617a45fa445cfa781bc50a/src/string.c#L7-L33

@liam-ilan More interesting thing now is what happens if you accidentally skip past end-of-line or end-of-string. The first one is now UB (similar to #5), the second one provides neat Python-like/C-macro-like way of writing `\n` as `\` followed by a newline (unless you're on Windows and reading file in binary mode).

**Comment by liam-ilan** [comment]
Fixed this one too! While using \ followed by a newline would have been cool, it too was undefined behavior (classic `\r\n` vs `\n`), so in commit bdfc557dedc26c1d75f169f48db36952945d1aba, error handling is done, even when the escape code is skipped on the first scan.
