### ISSUE TITLE
A bunch of undefined behavior in the lexer

### ISSUE THREAD

**Issue by yeputons** [liam-ilan/crumb#5]
The following snippet can access array out of bounds:

https://github.com/liam-ilan/crumb/blob/5ff70a23fa7df4bf8a6404ebbf164c54d7cac1a8/src/lex.c#L53-L66

Consider a string that terminates with `"`. The program enters the first `if` statement, increases `i`, now `code[i]` is `\0`. Then it enters the `while` loop, increases `i` one more time, now `code[i]` is out-of-bounds. It does not cause crash currently for me, though. You can also see a hint by passing `-fsanitize=address` to `gcc`/`clang`. 

Another issue is with `isdigit` function that [expects a non-negative number](https://en.cppreference.com/w/c/string/byte/isdigit), but you give it a `char` that can be (and typically) is signed: https://github.com/liam-ilan/crumb/blob/5ff70a23fa7df4bf8a6404ebbf164c54d7cac1a8/src/lex.c#L53-L66 . That is undefined behavior as well. I've seen such code crash on some systems in the past because `isdigit` was accessing an array under the hood, and negative index was very out-of-bounds.

**Comment by liam-ilan** [comment]
Hi @yeputons, I'm wondering what the remedy would be for the isdigit issue...
I'm new to C, so I'm not exactly familiar with best practices 😅...

**Comment by yeputons** [comment]
@liam-ilan I'm not great in C either, but I believe `isdigit((unsigned char)c)` should do the trick. `isdigit` actually expects "whatever fits into `unsigned char`", and `unsigned char` (likely) fits into `int`.

**Comment by liam-ilan** [comment]
Fixed in commit 5bfb7702047b4559cc7d55dc06f871273a4e7c95, thanks for the code review!
