### ISSUE TITLE
Accidentally quadratic lexer (`parseString`)

### ISSUE THREAD

**Issue by yeputons** [liam-ilan/crumb#6]
The following code has O(n^2) complexity (`n` is the length of `in`), [accidentally quadratic](https://accidentallyquadratic.tumblr.com/):

https://github.com/liam-ilan/crumb/blob/5ff70a23fa7df4bf8a6404ebbf164c54d7cac1a8/src/string.c#L13

Compile the interpreter with no optimizations and try to execute the output of the following Python program:

```python
print("(print\"" + "a" * int(1e6) + "\")")
```

It will take about 10^12 operations, seconds at the very least. `-O2` is typically smart enough to optimize reading `strlen()` on each iteration, but I would not rely on that.

**Comment by liam-ilan** [comment]
Fixed in commit 80ee6ce1c736022f8f8c3fe1c84ba4bf27f697b1. Good catch!
