### ISSUE TITLE
Make project open source?

### ISSUE THREAD

**Issue by Jookia** [liam-ilan/crumb#8]
Currently the project has no open source license, and neither do any contributions in the pull requests. Will this project be open sourced?

**Comment by liam-ilan** [comment]
I cannot provide a legally binding licence... I am a minor in BC 😅

**Comment by Jookia** [comment]
You have already provided a license for people to use this code under GitHub's terms of services. Why not expand that to open source?

**Comment by liam-ilan** [comment]
I am not a lawyer... I'm a minor 🥲... I cannot provide a license, not sure what GitHub's terms of services say 😅...

**Comment by entrptaher** [comment]
You dont have to be a lawyer to attach a license to be honest. It can be a MIT/GNU or even UNLICENCED. It simply states what people can do with the code and what not.

Do people have permission to modify and sell your code? Do they have to give credits? And so on.

Small questions are enough to keep this going.

**Comment by ronilan** [comment]
A license is a contract between the licensor and the licensee. For their protection contractual obligations made by minors are void. 

In some cases minors can enter into specific contracts (like work at certain age) or with expressed permission from their legal guardian (usually their parents). This is not such a case. 

IANAL
