### ISSUE TITLE
This project is fantastic and I appreciate you for putting this on here

### ISSUE THREAD

**Issue by IamDaedalus** [liam-ilan/crumb#9]
Just as the title says

I only started learning C early this year (late Jan early Feb) and reading through this code I'm impressed by how much I understand obviously from the fact that you wrote such concise and easy to understand code.

I've picked up on a few memory handling tricks along the way that I didn't think of and will actually be rewriting a simple interpreter-ish project I did a few weeks back (shameless plug [here](https://github.com/IamDaedalus/monty)) based on some of the practices I've picked up in this codebase

Thank you for sharing this project and writing neat concise code like this. I'm not done reading through everything but it's like a very good book you can't put down. I'm taking notes as I read in case I forget something

Anyway keep being awesome Liam 👍🏾

**Comment by liam-ilan** [comment]
Thanks @IamDaedalus :)

The best thing that could have ever come out of Crumb would be that someone would find it useful, so seeing this comment makes me really glad I succeeded!

p.s. your project looks awesome! Starred! 🌟
